### ISSUE TITLE
error when using FormControls -> patchValue/reset

### ISSUE THREAD

**Issue by varun-nambiar** [Harvest-Dev/ng-select2#1]
![image](https://user-images.githubusercontent.com/1249268/46804072-5d05c500-cd7f-11e8-98dd-3259c27b0b4c.png)

**Comment by varun-nambiar** [comment]
This is only when I have set multiple=true, and using patchValue to set default value.

**Comment by Zefling** [comment]
Patch on #2

**Comment by Zefling** [comment]
@varun-nambiar close this issue if this ok for you.
