### ISSUE TITLE
can this component dependencies be upgraded so we can use angular 10.x nicer

### ISSUE THREAD

**Issue by jcompagner** [Harvest-Dev/ng-select2#12]
without getting:

incompatible peer dependency

**Comment by jcompagner** [comment]
created a pull request for this: https://github.com/Harvest-Dev/ng-select2/pull/20

**Comment by Zefling** [comment]
Is it ok with 7.1.10 ?

**Comment by jcompagner** [comment]
the one i build my self seems fine
7.1.10 is not published to npm right? (i don't see that version yet)

**Comment by Zefling** [comment]
Sorry little mistake for my part. Now 7.1.10 is published.

**Comment by jcompagner** [comment]
yes it works, problem... angular 11 is just out ;)

and i tested the component now under 11 and it seems to me it works fine so the peer dependencies can be updated again..

  "@angular/common": "^7.0.0 || ^8.0.0 || ^9.0.0 || ^10.0.0 || ^11.0.0",
    "@angular/core": "^7.0.0 || ^8.0.0 || ^9.0.0 || ^10.0.0 || ^11.0.0"

of the package.json in the component

**Comment by Zefling** [comment]
Update :)

**Comment by Zefling** [comment]
@jcompagner  It's ok for you ?

**Comment by jcompagner** [comment]
yes seems fine
