### ISSUE TITLE
you can't have a value that is not in the data (list)

### ISSUE THREAD

**Issue by jcompagner** [Harvest-Dev/ng-select2#15]
because of this:

https://github.com/Harvest-Dev/ng-select2/blob/master/projects/ng-select2-component/src/lib/select2.component.ts#L684

it is not possible to have a value that is not in the list.
But for us this can happen, that a value was there before but is now not selectable anymore, they have to select another value..
But we still want to show that value, But te list just shouldn't show it anymore..

Is it possible to get some option that the value is not cleared but just showed?

**Comment by Zefling** [comment]
It's not really possible. It would be necessary to display a label which is not present in the list of options. What should be displayed if there is no label is at the value is something other than a string?

**Comment by Zefling** [comment]
With the last version, it's possible to hide an option in the drop-down list.

**Comment by jcompagner** [comment]
ah so we can show a none selectable value now?
i will test.

**Comment by Zefling** [comment]
Sorry, a little forgotten, the value is always selectable with keyboard. I'll fix that tomorrow.

**Comment by Zefling** [comment]
It is fixed.
