### ISSUE TITLE
append to body support

### ISSUE THREAD

**Issue by jcompagner** [Harvest-Dev/ng-select2#23]
Currently i don't see a way that we append the list/popup to the body 
Because of this if the select2 is limited to a container the list wil not show.

**Comment by Zefling** [comment]
Perhaps there should write the list display with the cdk overlay.
It would be a big change.

**Comment by jcompagner** [comment]
yeah i know i already looked at it a bit
not sure how for example the ng-bootstrap does it for its dropdown or typeahead:
https://ng-bootstrap.github.io/#/components/dropdown/examples#container

would be nice to follow that api

**Comment by Zefling** [comment]
I already did a similar thing here:
https://github.com/Harvest-Dev/ng-walkthrough/blob/master/projects/angular-walkthrough/src/lib/walkthrough.component.ts#L491

**Comment by Zefling** [comment]
Fixed in version 8.0.0
