### ISSUE TITLE
when select box is disable and title not removed

### ISSUE THREAD

**Issue by dchirag005** [Harvest-Dev/ng-select2#36]
![Screenshot (1)](https://user-images.githubusercontent.com/89446061/148052316-92bb6a44-0b2c-47f6-8dc2-5491412b9545.png)

- select box is disable time anyone user click to title with join 'X' sign then close event is run and title was remove outoff the box. 
- my question is  select box disable then not to remove title in box.

**Comment by Zefling** [comment]
Fixed in V8.0.6
