### ISSUE TITLE
Reset Value Single Select Undefined

### ISSUE THREAD

**Issue by DavidSegura** [Harvest-Dev/ng-select2#42]
Hi :D

I am implementing a dynamic component for some filters and I am using the ng-select 2 library.

The problem I have is the following, I declare a reactive form:

`private ngFormBuild(): void {
    let formFilter: FormControl[] = [];

    this.filters.forEach((filter: FilterTable) => {
      if (filter.type === FILTERS_TYPE.select) {
        formFilter[filter.label as any] = new FormControl(0);
      }

      if(filter.type === FILTERS_TYPE.select_multi) {
        formFilter[filter.label as any] = new FormControl([]);
      }

      if(filter.type === FILTERS_TYPE.text) {
        formFilter[filter.label as any] = new FormControl("");
      }
    });

    this.form = this.fb.group(formFilter);
  }
`
Then in the template I implement the selector:

` <ng-container *ngIf="f.type == FiltersEnum.select">
    <select2
      [attr.id]="f.label"
      [data]="ngGetSelect(f.label)"
      [resettable]="true"
      formControlName="{{ f.label }}"
      (update)="ngSubmit()"
    >
    </select2>
</ng-container>
`
When I load the view, the simple selector filter loads me with a default value, so far everything is correct.

![imagen](https://user-images.githubusercontent.com/20921548/198576744-b33bd5c5-f883-4157-9892-fa72fe844d31.png)

Then I select a value in the selector:

![imagen](https://user-images.githubusercontent.com/20921548/198576896-dfaf2d1a-7bb3-4b14-a7ab-c5e4e3535ef8.png)

And now when I delete the selection, the filter changes to undefined.

![imagen](https://user-images.githubusercontent.com/20921548/198577100-8f4b3e0a-c517-45c5-83db-d0df234a0c83.png)

I don't know if I'm doing something wrong. But shouldn't it return to the value of the FormControl?

![imagen](https://user-images.githubusercontent.com/20921548/198577179-b3f0514f-6237-4c07-8b98-a55c2c453364.png)

Thank you very much for your time

**Comment by Zefling** [comment]
Sorry, but I'm not sure I understand the problem. :(

**Comment by Zefling** [comment]
After rereading the problem. I understand better. Sorry.

You want an × to reset the value to the original one. But what you are asking is a special case. If the input value is 2 or an array of values, the × will no longer be consistent.

There should be an added option that resets to a given value.
