### ISSUE TITLE
How to dropdown working normal With search filter?

### ISSUE THREAD

**Issue by ketanpanther** [Harvest-Dev/ng-select2#43]
Hello, @Zefling 

i see your demo page in number 8 example in add search filter but they not working like number 9 example.
https://harvest-dev.github.io/ng-select2/dist/ng-select2/

How to working search filter with normal dropdown seach?

**Comment by Zefling** [comment]
It's a bug:

![image](https://user-images.githubusercontent.com/3032555/204258171-583a27a2-84c9-48c7-bf3a-13e67f648e6b.png)

**Comment by Zefling** [comment]
See #47
