### ISSUE TITLE
Search trigger not working

### ISSUE THREAD

**Issue by DavidSegura** [Harvest-Dev/ng-select2#47]
Good afternoon,

I have tested the library in a new project with angular 14. And the search event does not fire when I perform a search.

![image](https://user-images.githubusercontent.com/20921548/229111470-10fb051c-76df-49b5-9f38-8e86c4b994bf.png)
![image](https://user-images.githubusercontent.com/20921548/229111499-047462a8-42b3-48c7-bb85-e2459480f6e0.png)
![image](https://user-images.githubusercontent.com/20921548/229111519-e2f6d49e-7d53-44e7-9585-70606ec41760.png)
![image](https://user-images.githubusercontent.com/20921548/229111659-ae755cb2-578e-414f-b5e5-7fe91a231113.png)

Thanks for your time

**Comment by Zefling** [comment]
This parameter is required: `customSearchEnabled`

```
<select2 [data]="data"
         customSearchEnabled
         (search)="_search($event)"></select2>
```

**Comment by Zefling** [comment]
I change the generator to indicate this.

**Comment by mcfdez** [comment]
Same problem in Angular 16:

```
<div class="mt-5">
    <form>
        <div class="form-group row">
            <div class="col-md-4">
                <div style="width: 100%">
                    <div class="input-group">
                        <select2
                            customSearchEnabled
                            [data]="data"
                            (search)="searchTrack($event)"
                            displaySearchStatus="always"
                            placeholder="Select track"
                        ></select2>
                        <div class="input-group-prepend">
                            <button class="btn btn-primary" type="button"><i class="fa fa-plus"></i></button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
```

```
export class SessionsAddTracksComponent {
    public data = [
        { value: 1, label: 'hola' },
    ];

    /**
     * On search track
     */
    public searchTrack(event: Select2SearchEvent): void {
        console.log(event);
    }
}
```

The searchTrack method is never fired. What could be happening?

**Comment by Zefling** [comment]
Please open a new issue. @mcfdez
