### ISSUE TITLE
I'd like to let the user type their own choices into the box when "multiple" is true

### ISSUE THREAD

**Issue by sirenbrian** [Harvest-Dev/ng-select2#48]
Hello,
We're trying to use this component in a situation where the user can either pick items from the dropdown list, or enter their own values, or some combination of both.  We tried other ngSelect2 wrappers, which did allow this behavior, but we'd prefer to use this one since it doesn't require jQuery to be installed.

Is there a combination of parameters that would allow this behavior? I think the underlying select2  component allows it.

I'm using v9.0.0 because we're on Angular 13.

**Comment by Zefling** [comment]
Do you have a more explicit example for input values?

**Comment by sirenbrian** [comment]
Any free text like "hello", "blah blah", "foo bar flippy doo dah".  We don't need to support CRLF in there - no line breaks, but otherwise any free text is allowed.  The output of the control would then include that free text as one of the values that the user put into the control.

**Comment by dadoadk** [comment]
I need the same feature. Our user should be able to select from suggested list of choices, select multiple choices, and in addition add a free text. 
![image](https://user-images.githubusercontent.com/11295452/231848312-ca95b011-32be-4c07-8371-444dd2b76090.png)
![image](https://user-images.githubusercontent.com/11295452/231848341-2e3193bc-16c3-4c1a-a7d5-6bea8a6be8ce.png)

**Comment by Zefling** [comment]
See version 11.1.0

**Comment by sirenbrian** [comment]
Thank you, we really appreciate you adding this feature!
