### ISSUE TITLE
Close 'multiple' dropdown when item is chosen and when clicking outside of component

### ISSUE THREAD

**Issue by vincentsels** [Harvest-Dev/ng-select2#52]
In `multiple` mode, it seems that currently, when you select an item, the dropdown list does not get closed. Even clicking outside of the component does not seem to close it. The only thing that seems to close it is pressing escape (when the component is focussed).

I find it surprising that clicking outside of the component does not close the dropdown list. This seems like a bug.

Closing the dropdown list when an option is chosen is debatable. In scenarios where users typically need to select multiple that makes sense, if in most use cases only one is selected, it is more annoying. It might make sense to have an option to toggle this.

**Comment by Zefling** [comment]
Probably fixed in 13.0.0
