### ISSUE TITLE
Use of Template for rending multiple Selection

### ISSUE THREAD

**Issue by majora2007** [Harvest-Dev/ng-select2#54]
I'm wondering if it would be possible to augment the library to provide a custom html element via template for multiple selection. 

I'm currently trying to integrate this into my application and provide the same Look and Feel as my existing setup. Unfortunately, the existing structure does not allow for much customization. Here is what I was able to achieve:

![image](https://github.com/Harvest-Dev/ng-select2/assets/735851/0f8506b3-6853-431a-970e-fe7231f6aa6a)

vs existing:
![image](https://github.com/Harvest-Dev/ng-select2/assets/735851/72eff663-55a8-404b-abe3-043b993931a6)

I am willing to submit a PR, but want to validate before I spend the time.

**Comment by Zefling** [comment]
With version 13.0.4, is it ok?
I corrected other points.

**Comment by majora2007** [comment]
I'm on holiday, but will check once I'm back.
