### ISSUE TITLE
Single Select Add New

### ISSUE THREAD

**Issue by majora2007** [Harvest-Dev/ng-select2#55]
I'm trying to use this to add a new item to a list of existing options (autoCreate), however i do not see any input.

From the documentation and the code it seems possible, but I'm not seeing how to get it to happen. (Edit: It doesn't seem possible on single mode)

If this is not possible, are you open to a PR or enhancement? I really need this ability along with a separate event for when a new item is added (multiple or not). 

```
<select2 [data]="smartFilters"
                     id="filter-name"
                     formControlName="name"
                     (update)="updateFilterValue($event)"
                     [autoCreate]="true"
                     [multiple]="false"
                     [infiniteScroll]="false"
                     [resettable]="true">
            </select2>
```
![image](https://github.com/Harvest-Dev/ng-select2/assets/735851/1e231853-c8f0-4110-b30d-a8aa4319d650)

**Comment by Zefling** [comment]
I'm sorry, currently `autoCreate` is only available with `multiple=true`

In single mode, the field just needs to be editable. We should see how to integrate without breaking the use of templates.

**Comment by majora2007** [comment]
I'll take a few stabs at it. I'm yet again going on a holiday, so I wont get to it till + 1 week's time.

**Comment by majora2007** [comment]
Just got back from holiday, so will take a stab at this.

**Comment by Zefling** [comment]
See version 13.0.9  ;)

**Comment by majora2007** [comment]
Thanks! As I was integrating, I thought of some small enhancements to streamline the UX. I'll try to get a PR open for discussion.
