### ISSUE TITLE
How to avoid unnecessary execution of update() (to make update() only work when the user selects an item)

### ISSUE THREAD

**Issue by nouaim** [Harvest-Dev/ng-select2#65]
`<select2
              [data]="choices"
              [value]="value"
              placeholder="select or add a type"
              minCountForSearch="0"
              autoCreate="true"
              (update)="update(file, $event)"
            >
            </select2>`

When we open the component, the function `update()` gets executed though the user hasn't clicked or done any action, how can we stop this behavior and make `update()` only run if the user selects an item.

**Comment by nouaim** [comment]
@Zefling console anything in the update function, you will see it gets prints although the user hasn't interacted at with the select2 field

**Comment by Tibasa** [comment]
Same problem.

**Comment by nouaim** [comment]
@Tibasa i got the answer here https://github.com/Harvest-Dev/ng-select2/issues/71#issuecomment-2258546149

**Comment by Tibasa** [comment]
> @Tibasa i got the answer here [#71 (comment)](https://github.com/Harvest-Dev/ng-select2/issues/71#issuecomment-2258546149)

Thanks!!! I installed 15.0.1 and the problem was resolved.
