### ISSUE TITLE
Initating select2 with multiselect value is not working in version 15.0.1

### ISSUE THREAD

**Issue by Birte-Teal** [Harvest-Dev/ng-select2#73]
Hello

I upgraded the ng-select2-component package to the latest version of 15.0.1.

Unfortunately this broke my multiselect when setting a default value.
I went down a version (15.0.0) and it works perfectly fine.

Hopefully this can be fix in future versions.

**Comment by Zefling** [comment]
I think it's fixed. You can try with `15.1.0`
