### ISSUE TITLE
console.error left over in the code?

### ISSUE THREAD

**Issue by jcompagner** [Harvest-Dev/ng-select2#75]
this commit 
https://github.com/Harvest-Dev/ng-select2/commit/083f662cdc19d3ea4bc016c8dddccc240c3f91a7#diff-9e1a27ae206cc88f0235003fbfc84b563f72997c07ab3a6f9c26817b0f3f6f99R987

adds that console.error message: https://github.com/Harvest-Dev/ng-select2/blob/master/projects/ng-select2-component/src/lib/select2.component.ts#L1007
is that really a thing you want to report? (then i guess the message should be more clear)
or is that really a left over from some debugging?

**Comment by Zefling** [comment]
Indeed, this is a debugging oversight.
I will remove this.
