### ISSUE TITLE
Label language is not updated

### ISSUE THREAD

**Issue by mirlayne** [Harvest-Dev/ng-select2#81]
Hello,

When the language is changed the label of the select2 component  keeps the old language. For reference check `31. change list (french)` in https://harvest-dev.github.io/ng-select2/dist/ng-select2/browser/

![image](https://github.com/user-attachments/assets/68b44d33-fdcf-4f41-a343-93548d0bb950)

**Comment by Zefling** [comment]
Fix in 15.3.0
